/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.*;
import java.lang.reflect.Type;
import java.util.List;

public class App {

    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();
        File file = new File("app/src/main/resources/recentquotes.json");
        FileReader reader = new FileReader(file);
        Quotes[] fileString = gson.fromJson(reader, Quotes[].class);
        int arrayLength = fileString.length;
        int random = (int)(Math.random() * arrayLength);
        System.out.println(fileString[random]);











    }
}
